### PR TITLE
Use dumb init instead of s6

### PR DESCRIPTION
**Pull request by alexdias**

### CODE REVIEW

**Review by tomashley — CHANGES_REQUESTED** [review]
Can you drop this back to `alpine` as the base image and see if that still works?

The smebberson base image is specifically for the s6 overlay and we don't need it if we do this

**Comment by alexdias** [comment]
@tomashley Ah, of course! I'll give it a shot

**Comment by alexdias** [comment]
@tomashley Updated

**Review by tomashley — APPROVED** [review]

**Comment by thibaultlaurens** [comment]
I have tested this while referencing the agent as https://github.com/outlyerapp/agent/pull/58 on a local kubernetes cluster and it works, the kubernetes cluster stay alive when I delete our daemonset

**Review by thibaultlaurens — APPROVED** [review]

**Pull request merged**
